ITEM.name = "Награда"
ITEM.desc = "Награда за убийство НПЦ."
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.invWidth = 5
ITEM.invHeight = 5
ITEM.category = "Storage"
ITEM.permit = "misc"
ITEM.noTake = true
ITEM.notTransfered = true