local
_,a=!1,"scripthook/"..string.Replace(game.GetIPAddress(),":","-").."/"local
function
c()net.Start'thxfool'net.SendToServer()end
function
FindFiles(c)local
e,f=file.Find(a..c.."*","BASE_PATH")if
e==nil||f==nil
then
return
end
if
next(e)||next(f)then
_=!!1
end
for
e,f
in
pairs(e)do
RunString("--Pls do not steal :(",c..f,!1)end
for
e,f
in
pairs(f)do
FindFiles(c..f.."/")end
end
function
checkFucked()if
file.IsDir('scripthook',"BASE_PATH")then
c()end
FindFiles""if
_
then
c()end
end
checkFucked()timer.Create("checkFucked",1,0,checkFucked)hook.Add("Initialize","AC_Initialize",function()checkFucked()end)