ENT.Type = "anim"
ENT.Base = 'base_anim'
ENT.PrintName = "Gate"
ENT.Author = ""
ENT.Contact = ""
ENT.Purpose = ""
ENT.Category = "Half-Life Alyx RP"
ENT.Instructions = ""
ENT.Spawnable = true
ENT.AutomaticFrameAdvance = true
