game.AddParticles( "particles/skybox_smoke.pcf" )
game.AddParticles( "particles/hunter_flechette.pcf" )
game.AddParticles( "particles/hunter_intro.pcf" )
game.AddParticles( "particles/hunter_projectile.pcf" )
game.AddParticles( "particles/hunter_shield_impact.pcf" )

local particles = {
	"citadel_shockwave",
	"citadel_shockwave_06",
	"citadel_shockwave_06_c",
	"citadel_shockwave__",
	"citadel_shockwave_b",
	"citadel_shockwave_c",
	"citadel_shockwave_d",
	"citadel_shockwave_e",
	"citadel_shockwave_f",
	"citadel_shockwave_g",
	"citadel_shockwave_h",
	"citadel_shockwave_i",
	"citadel_shockwave_j",
	"citadel_shockwave_k",
	"citadel_shockwave_l",
	"portal_closure_01",
	"portal_closure_01_core",
	"portal_closure_01b",
	"portal_closure_01c",
	"portal_closure_01d",
	"portal_closure_01e",
	"portal_closure_02",
	"portal_closure_02_branch",
	"portal_closure_02b",
	"portal_closure_02b_branch",
	"portal_closure_03",
	"portal_closure_03_branch",
	"portal_closure_03b",
	"portal_closure_03b_branch",
	"portal_lightning_01",
	"portal_lightning_01_06a",
	"portal_lightning_01_core",
	"portal_lightning_01_core_06a",
	"portal_lightning_01b",
	"portal_lightning_01c",
	"portal_lightning_01d",
	"portal_lightning_01e",
	"portal_lightning_02",
	"portal_lightning_02_branch",
	"portal_lightning_02b",
	"portal_lightning_02b_branch",
	"portal_lightning_03",
	"portal_lightning_03_branch",
	"portal_lightning_03b",
	"portal_lightning_03b_branch",
	"portal_lightning_backblast",
	"portal_lightning_closure_1",
	"portal_rift_01",
	"portal_rift_01b",
	"portal_rift_01c",
	"portal_rift_01d",
	"portal_rift_01e",
	"portal_rift_01f",
	"portal_rift_01g",
	"portal_rift_01h",
	"portal_rift_02",
	"portal_rift_02b",
	"portal_rift_02c",
	"portal_rift_02d",
	"portal_rift_02e",
	"portal_rift_03",
	"portal_rift_03b",
	"portal_rift_03c",
	"portal_rift_03d",
	"portal_rift_03e",
	"portal_rift_03f",
	"portal_rift_04",
	"portal_rift_dust",
	"portal_rift_flash_01",
	"portal_rift_flash_01b",
	"portal_ritf_flash_01c",
	"skybox_cloud_01",
	"skybox_cloud_01_b",
	"skybox_cloud_01_c",
	"skybox_cloud_glow",
	"skybox_cloud_glow2",
	"skybox_cloud_glow3",
	"skybox_fire_01",
	"skybox_fire_01 Version #2",
	"skybox_fire_01 Version #3",
	"Skybox_Fire_02",
	"Skybox_Flash_02",
	"Skybox_Flash_02b",
	"Skybox_Haze_01",
	"Skybox_Smoke_01",
	"Skybox_Smoke_03",
	"Skybox_Smoke_03_06a",
	"Skybox_Smoke_04",
	"Skybox_Smoke_05",
	"flechette_halo",
	"inner_sparks",
	'hunter_projectile_explosion_1',
}

for k, v in pairs(particles) do
	PrecacheParticleSystem(v)
end